apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/sclorg/django-ex.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: django
    app.kubernetes.io/component: django
    app.kubernetes.io/instance: django
    app.kubernetes.io/name: django
    app.kubernetes.io/part-of: python
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: django
spec:
  lookupPolicy:
    local: false
